ytdl -o "{title}" https://www.youtube.com/watch?v=sQCqVBuq-gA&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=2&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=dIJXSNXRL9c&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=3&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=pkT1asykALk&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=4&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=9bkBfUq1Lt8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=5&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=SYMK9_Jtbw4&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=6&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=FQ8gbMr0Pcc&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=7&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=8_xPSlLXxu0&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=8&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=vmoMwYwDQ-w&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=9&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=o4R2VNzeDhY&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=10&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=E0HxQlVhsr8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=11&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=uWHui1WfxPY&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=12&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=NHgm7dBorRY&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=13&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=2-HUwnEn2VM&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=14&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=kGHcq2fF73g&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=15&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=7wwGUDUGb6c&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=16&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=sdkLuWykdkI&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=17&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=fVg0KueOgY8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=18&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=EydPKKuOg28&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=19&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=RW9xaZajQn8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=20&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=ninc1T81WXo&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=21&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=JOjwYKIdgog&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=22&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=SOX5IBlv1l0&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=23&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=atG8NHLqps8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=24&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=bNh814RhTjo&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=25&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=oDGi-Sbj0O0&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=26&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=hFsYCf6LuNQ&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=27&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=6Jr7xOLF4DM&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=28&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=TDEVr6s9mqE&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=29&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=cnPNhhm1Iy4&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=30&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=Gw7tTcFEhHs&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=31&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=aAYcimORPOg&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=32&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=PqPk0cp-gh4&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=33&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=L5ETyxS1ea8&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=34&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=nAe0HUrLvo0&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=35&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=GbYrejBhJds&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=36&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=7soXrrsiLGA&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=37&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=oI-CQBKWbDY&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=38&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=6Ddb0CtLcME&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=39&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=uLGl0mu4rKA&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=40&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=1R56X8rQaGc&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=41&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=eQ5g4fCxf0M&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=42&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=GYiJ27lCBCU&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=43&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=pdha1IIG36c&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=44&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=Ri0i101p5Sc&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=45&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=zv8S7UlVryA&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=46&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=_DPOtHUv0n4&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=47&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=fuOnsFN4cVY&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=48&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=5i-Gw7OC7oo&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=49&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=BxFYmBYBmaU&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=50&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=5MYlSn-wR5g&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=51&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=JrnsaKb2rnw&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=52&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=s9GCTLd6-AM&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=53&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=kP8aTueFlCs&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=54&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=RefwcEA2Wv4&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=55&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=V1BwIgIN_qA&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=56&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=ljD_P0S6SDI&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=57&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=BS4Wh0qvOkc&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=58&t=0s &
ytdl -o "{title}" https://www.youtube.com/watch?v=DHtcDh3ZwFw&list=PLnMKNibPkDnGtuIl5v0CvC81Am7SKpj02&index=59&t=0s &